WARDS = [
    {
        "ward_id": "DHK-001",
        "ward_name": "Mirpur",
        "lat": 23.82,
        "lon": 90.36,
        "drainage_coefficient": 0.3,
        "population_density": 45000,
    },
    {
        "ward_id": "DHK-002",
        "ward_name": "Dhanmondi",
        "lat": 23.74,
        "lon": 90.37,
        "drainage_coefficient": 0.6,
        "population_density": 32000,
    },
    {
        "ward_id": "DHK-003",
        "ward_name": "Gulshan",
        "lat": 23.78,
        "lon": 90.41,
        "drainage_coefficient": 0.7,
        "population_density": 18000,
    },
    {
        "ward_id": "DHK-004",
        "ward_name": "Mohakhali",
        "lat": 23.77,
        "lon": 90.4,
        "drainage_coefficient": 0.4,
        "population_density": 38000,
    },
    {
        "ward_id": "DHK-005",
        "ward_name": "Banani",
        "lat": 23.79,
        "lon": 90.4,
        "drainage_coefficient": 0.65,
        "population_density": 22000,
    },
    {
        "ward_id": "DHK-006",
        "ward_name": "Uttara",
        "lat": 23.87,
        "lon": 90.4,
        "drainage_coefficient": 0.55,
        "population_density": 28000,
    },
    {
        "ward_id": "DHK-007",
        "ward_name": "Tejgaon",
        "lat": 23.76,
        "lon": 90.39,
        "drainage_coefficient": 0.35,
        "population_density": 41000,
    },
    {
        "ward_id": "DHK-008",
        "ward_name": "Lalbagh",
        "lat": 23.72,
        "lon": 90.38,
        "drainage_coefficient": 0.25,
        "population_density": 55000,
    },
    {
        "ward_id": "DHK-009",
        "ward_name": "Hazaribagh",
        "lat": 23.72,
        "lon": 90.37,
        "drainage_coefficient": 0.2,
        "population_density": 52000,
    },
    {
        "ward_id": "DHK-010",
        "ward_name": "Rayer Bazar",
        "lat": 23.73,
        "lon": 90.36,
        "drainage_coefficient": 0.3,
        "population_density": 44000,
    },
]

WEATHER = {
    "DHK-001": {
        "rainfall_3day_mm": 52,
        "humidity_percent": 88,
        "sunlight_hours": 3.2,
        "temp_max": 34,
        "temp_min": 26,
    },
    "DHK-002": {
        "rainfall_3day_mm": 28,
        "humidity_percent": 75,
        "sunlight_hours": 6.1,
        "temp_max": 33,
        "temp_min": 25,
    },
    "DHK-003": {
        "rainfall_3day_mm": 18,
        "humidity_percent": 70,
        "sunlight_hours": 7.4,
        "temp_max": 32,
        "temp_min": 24,
    },
    "DHK-004": {
        "rainfall_3day_mm": 45,
        "humidity_percent": 84,
        "sunlight_hours": 4.0,
        "temp_max": 34,
        "temp_min": 26,
    },
    "DHK-005": {
        "rainfall_3day_mm": 22,
        "humidity_percent": 72,
        "sunlight_hours": 6.8,
        "temp_max": 33,
        "temp_min": 25,
    },
    "DHK-006": {
        "rainfall_3day_mm": 15,
        "humidity_percent": 68,
        "sunlight_hours": 8.2,
        "temp_max": 32,
        "temp_min": 24,
    },
    "DHK-007": {
        "rainfall_3day_mm": 48,
        "humidity_percent": 86,
        "sunlight_hours": 3.8,
        "temp_max": 35,
        "temp_min": 27,
    },
    "DHK-008": {
        "rainfall_3day_mm": 55,
        "humidity_percent": 91,
        "sunlight_hours": 2.9,
        "temp_max": 35,
        "temp_min": 28,
    },
    "DHK-009": {
        "rainfall_3day_mm": 51,
        "humidity_percent": 89,
        "sunlight_hours": 3.1,
        "temp_max": 35,
        "temp_min": 27,
    },
    "DHK-010": {
        "rainfall_3day_mm": 47,
        "humidity_percent": 85,
        "sunlight_hours": 4.2,
        "temp_max": 34,
        "temp_min": 26,
    },
}

DISPATCH_ORDERS = [
    {
        "ward_id": "DHK-001",
        "ward_name": "Mirpur",
        "swapi_score": 0.91,
        "officer_count": 4,
        "larvicide_litres": 22.0,
        "target_sector": "Eastern construction zones, Section 10",
        "llm_reasoning": "Mirpur has SWAPI 0.91 driven by 52mm rainfall and 88% humidity. Historical DGHS data shows peak 847 cases in 2022 under identical conditions. Section 10 construction sites have active water accumulation requiring immediate larviciding.",
        "rag_citation": "WHO: larvicide 1mg/L for collections >4 days. DGHS 2022: Mirpur week-32 peak 847 cases.",
    },
    {
        "ward_id": "DHK-008",
        "ward_name": "Lalbagh",
        "swapi_score": 0.87,
        "officer_count": 3,
        "larvicide_litres": 18.0,
        "target_sector": "Old city drainage channels and rooftops",
        "llm_reasoning": "Lalbagh has lowest drainage coefficient (0.25) combined with 91% humidity — highest in the city. Dense old-city housing traps water in rooftop tanks and blocked gutters. Immediate deployment to northern sector recommended.",
        "rag_citation": "WHO: priority sites include rooftop tanks and blocked gutters. DGHS: Lalbagh drainage index bottom quartile historically.",
    },
    {
        "ward_id": "DHK-009",
        "ward_name": "Hazaribagh",
        "swapi_score": 0.84,
        "officer_count": 3,
        "larvicide_litres": 16.0,
        "target_sector": "Industrial zone water containers",
        "llm_reasoning": "Hazaribagh industrial area has numerous uncovered water containers and drainage_coefficient of 0.20. 51mm rainfall combined with 89% humidity creates critical breeding window. Industrial water barrels are primary vector.",
        "rag_citation": "WHO: construction and industrial water containers are high-priority breeding sites. DGHS: industrial zones 3x average case density.",
    },
    {
        "ward_id": "DHK-004",
        "ward_name": "Mohakhali",
        "swapi_score": 0.78,
        "officer_count": 2,
        "larvicide_litres": 12.0,
        "target_sector": "Market area and residential rooftops",
        "llm_reasoning": "Mohakhali market area generates standing water daily from vendor activity. SWAPI 0.78 with 45mm rainfall requires precautionary dispatch before breeding cycle completes in 4-5 days.",
        "rag_citation": "WHO: act before 4-5 day breeding cycle completes. DGHS: market areas 2x residential case rate.",
    },
    {
        "ward_id": "DHK-007",
        "ward_name": "Tejgaon",
        "swapi_score": 0.75,
        "officer_count": 2,
        "larvicide_litres": 10.0,
        "target_sector": "Factory compounds and low-lying areas",
        "llm_reasoning": "Tejgaon factory zone has drainage_coefficient 0.35 with 48mm rainfall. Low-lying factory compounds accumulate water during monsoon. Two officers can cover the primary industrial cluster efficiently.",
        "rag_citation": "WHO: low-lying industrial areas require systematic inspection. DGHS: Tejgaon monsoon surge pattern consistent 2019-2023.",
    },
]

LLM_QA = {
    "Which 5 wards need dispatch today?": "Based on current SWAPI scores, the top 5 wards requiring immediate dispatch are:\n\n1. **Mirpur** (SWAPI: 0.91 — CRITICAL) — 4 officers, 22L larvicide, Section 10 construction\n2. **Lalbagh** (SWAPI: 0.87 — CRITICAL) — 3 officers, 18L, old city drainage channels\n3. **Hazaribagh** (SWAPI: 0.84 — CRITICAL) — 3 officers, 16L, industrial zone containers\n4. **Mohakhali** (SWAPI: 0.78 — HIGH) — 2 officers, 12L, market area rooftops\n5. **Tejgaon** (SWAPI: 0.75 — HIGH) — 2 officers, 10L, factory compounds\n\nTotal resources needed: **14 officers, 78 litres larvicide**.\n\n*Source: WHO larviciding protocol + DGHS monsoon surge pattern 2019-2023*",
    "What is the risk in Mirpur right now?": "**Mirpur — CRITICAL RISK (SWAPI: 0.91)**\n\nCurrent conditions driving this score:\n- Rainfall: 52mm over last 3 days (well above 20mm threshold)\n- Humidity: 88% (optimal mosquito survival range)\n- Sunlight: only 3.2 hours/day (slow water evaporation)\n\n6 citizen reports verified in the last 24 hours. Historical context: Mirpur recorded **847 cases in week 32 of 2022** under nearly identical weather conditions.\n\n**Recommended action:** 4 field officers to Section 10 construction zone. Apply 22 litres larvicide at 1mg/L concentration. Target rooftop water collections and construction site containers.\n\n*Source: DGHS surveillance 2022, WHO vector control protocol*",
    "How much larvicide do we need this week?": "Based on current SWAPI scores across all 10 monitored wards:\n\n**Total estimated requirement: 94 litres**\n\nBreakdown by risk level:\n- Critical wards (SWAPI >0.7): Mirpur + Lalbagh + Hazaribagh + Mohakhali + Tejgaon = **78L**\n- Moderate wards (SWAPI 0.3-0.7): Dhanmondi + Mohakhali buffer = **10L**\n- Precautionary (remaining wards): **6L**\n\nRecommend pre-positioning **100 litres at DNCC central depot** to cover surge demand.\n\n*Source: WHO larvicide dosing guidelines 1mg/L per water collection volume*",
    "How many citizen reports today?": "**23 citizen reports received today** across all 10 wards.\n\nVerification breakdown:\n- Verified (stagnant water confirmed): **18 reports** (78% verification rate)\n- Rejected (no water detected): 5 reports\n\nTop reporting wards:\n1. Mirpur — 8 verified reports\n2. Lalbagh — 5 verified reports\n3. Hazaribagh — 3 verified reports\n\nAll 18 verified reports have been added to the GPS detection layer and forwarded to the dispatch queue.\n\n*AI verification powered by YOLOv11 — average confidence: 0.87*",
    "What is the SWAPI formula?": "**SWAPI = tanh(w₁·R + w₂·H + w₃·(1-S) + w₄·T_range + w₅·D_inv)**\n\nWhere:\n- **R** = normalized 3-day rainfall accumulation\n- **H** = relative humidity (0-1)\n- **S** = sunlight duration ratio (0-1)\n- **T_range** = diurnal temperature range factor\n- **D_inv** = inverse drainage coefficient\n\nWeights learned from DGHS 2015-2023 case data:\n- w₁=0.35 (rainfall is primary driver)\n- w₂=0.25 (humidity second)\n- w₃=0.20 (low sunlight = slow evaporation)\n- w₄=0.10 (temperature range)\n- w₅=0.10 (drainage quality)\n\nOutput range: -1 (very safe) to +1 (critical)\nTrigger thresholds: >0.5 activates satellite pipeline, >0.7 triggers SMS alerts",
}

WHO_KNOWLEDGE = [
    {
        "id": 1,
        "source": "WHO Guidelines",
        "content": "Aedes aegypti larvae develop in stagnant clean water. Larval source reduction is the primary prevention method. Apply larvicide (temephos or Bti) to water collections that cannot be eliminated. Recommended concentration: 1mg/L for temephos. Priority sites: construction containers, rooftop tanks, flower pots, discarded tires, blocked gutters. High-risk threshold: stagnant water persisting more than 4-5 days at temperatures above 25°C.",
    },
    {
        "id": 2,
        "source": "DGHS Records",
        "content": "Dhaka accounts for 60% of national cases annually. Peak transmission: July-October monsoon season. Highest case burden in Mirpur, Mohakhali, Tejgaon, Lalbagh. 2023 outbreak: 321,179 hospitalized, 1,705 deaths. Risk amplifiers: construction zones, low-lying drainage areas, informal settlements. Breeding cycle completes in 7-10 days at 25-30°C.",
    },
    {
        "id": 3,
        "source": "BMD Climate Data",
        "content": "Critical dengue risk window: 3+ consecutive days with rainfall >20mm, humidity >80%, temperature 25-32°C. Diurnal temperature range below 8°C indicates high humidity retention favoring mosquito survival. Sunlight hours below 6 per day reduces evaporation and increases stagnant water persistence. Annual Dhaka rainfall: 1,854mm concentrated June-September.",
    },
]

CITIZEN_REPORT_COUNTS = {
    "DHK-001": 8,
    "DHK-002": 2,
    "DHK-003": 1,
    "DHK-004": 3,
    "DHK-005": 2,
    "DHK-006": 1,
    "DHK-007": 2,
    "DHK-008": 5,
    "DHK-009": 3,
    "DHK-010": 2,
}
